spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/VCORE
    username: postgres
    password: 1234
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email Configuration (Requires an API Key from an email provider like Resend or SendGrid)
  email:
    api-key: "re_MqBeboYh_9nmqDxeovFheLBcdt5phcVoK"

  # Gmail SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: "vexcorespng@gmail.com"
    password: "gzic jwgw yxvt wfos"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  owner:
    email: vexcorespng@gmail.com
