sonar.projectKey=VeXero_VCORES
sonar.organization=vexero
sonar.host.url=https://sonarcloud.io

sonar.sources=VCORE/src/main/java
sonar.tests=VCORE/src/test/java
sonar.java.binaries=VCORE/target/classes

sonar.junit.reportPaths=VCORE/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=VCORE/target/site/jacoco/jacoco.xml

sonar.exclusions=**/*Application.java,**/config/**,**/dto/**,**/model/**
